import pandas as pd
import matplotlib.pyplot as plt

# Set column names
colnames = ['JURISDICTION_NAME', 'COUNT_PARTICIPANTS', 'COUNT_FEMALE', 'PERCENT_FEMALE', 'COUNT_MALE', 'PERCENT_MALE',
            'COUNT_GENDER_UNKNOWN',
            'PERCENT_GENDER_UNKNOWN', 'COUNT_GENDER_TOTAL', 'PERCENT GENDER TOTAL', 'COUNT PACIFIC ISLANDER',
            'PERCENT PACIFIC ISLANDER', 'COUNT HISPANIC LATINO', 'PERCENT HISPANIC LATINO', 'COUNT AMERICAN INDIAN',
            'PERCENT AMERICAN INDIAN', 'COUNT ASIAN NON HISPANIC', 'PERCENT ASIAN NON HISPANIC',
            'COUNT WHITE NON HISPANIC',
            'PERCENT WHITE NON HISPANIC', 'COUNT BLACK NON HISPANIC', 'PERCENT BLACK NON HISPANIC',
            'COUNT OTHER ETHNICITY',
            'PERCENT OTHER ETHNICITY', 'COUNT ETHNICITY UNKNOWN', 'PERCENT ETHNICITY UNKNOWN', 'COUNT ETHNICITY TOTAL',
            'PERCENT ETHNICITY TOTAL', 'COUNT PERMANENT RESIDENT ALIEN', 'PERCENT PERMANENT RESIDENT ALIEN',
            'COUNT US CITIZEN',
            'PERCENT US CITIZEN', 'COUNT OTHER CITIZEN STATUS', 'PERCENT OTHER CITIZEN STATUS',
            'COUNT CITIZEN STATUS UNKNOWN',
            'PERCENT CITIZEN STATUS UNKNOWN', 'COUNT CITIZEN STATUS TOTAL', 'PERCENT CITIZEN STATUS TOTAL',
            'COUNT RECEIVES PUBLIC ASSISTANCE', 'PERCENT RECEIVES PUBLIC ASSISTANCE',
            'COUNT NRECEIVES PUBLIC ASSISTANCE',
            'PERCENT NRECEIVES PUBLIC ASSISTANCE', 'COUNT PUBLIC ASSISTANCE UNKNOWN',
            'PERCENT PUBLIC ASSISTANCE UNKNOWN',
            'COUNT PUBLIC ASSISTANCE TOTAL', 'PERCENT PUBLIC ASSISTANCE TOTAL']

# Get data from data file
data = pd.read_csv("C:\\Users\\laure\\OneDrive\\Documents\\Purdue\\IN300 - Programming for Data Analysis\\Unit "
                   "8\\Demographic_Statistics_By_Zip_Code.csv", names=colnames)

plt.scatter(data.COUNT_FEMALE, data.COUNT_MALE, s=200)

plt.show()
